### ISSUE TITLE
Операторы сравнения векторов

### ISSUE THREAD

**Issue by avasyukov** [Shrulk/Linear_Algebra#2]
Их можно или починить, или убрать (так-то их не было в требованиях).

1. Равенство
https://github.com/Shrulk/Linear_Algebra/blob/9e09db5bba869bf0cc60ef63d6cf57aeb1c8f7fe/main.cpp#L45-L47
Числа с плавающей точкой не стоит сравнивать на строгое равенство - оно не достигается примерно никогда. Нужно ввести какой-нибудь малый epsilon и сравнивать с ним модуль разности.

2. Неравенство
https://github.com/Shrulk/Linear_Algebra/blob/9e09db5bba869bf0cc60ef63d6cf57aeb1c8f7fe/main.cpp#L49-L51
Сейчас требуется отличие всех координат, что нелогично. Можно руками выписать новое условие. Но можно сделать просто ```return !(*this == v2);```

**Comment by Shrulk** [comment]
Исправил
